--------------------------------------------------------
--  DDL for Table TRUST
--------------------------------------------------------

  CREATE TABLE "ESCHEATMENT"."TRUST" 
   (	"TRUST_ID" NUMBER(10,0), 
	"TRUST_NUM" VARCHAR2(8 BYTE), 
	"MARKED_AS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"STATUS_ID" NUMBER(*,0), 
	"DELETE_IND" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ON_HOLD_IND" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CREATE_USER_ID" VARCHAR2(40 BYTE), 
	"CREATE_DT" DATE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE), 
	"UPDATE_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRUST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESCHEATMENT"."TRUST_PK" ON "ESCHEATMENT"."TRUST" ("TRUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRUST
--------------------------------------------------------

  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("DELETE_IND" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("MARKED_AS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("TRUST_NUM" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("TRUST_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" ADD CONSTRAINT "TRUST_PK" PRIMARY KEY ("TRUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("UPDATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("CREATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("CREATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."TRUST" MODIFY ("ON_HOLD_IND" NOT NULL ENABLE);
