
  CREATE TABLE "ESCHEATMENT"."TRUST" 
   (	"TRUST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TRUST_NUM" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"MARKED_AS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"STATUS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"DELETE_IND" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"ON_HOLD_IND" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"CREATE_USER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CREATE_DT" DATE NOT NULL ENABLE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"UPDATE_DT" DATE NOT NULL ENABLE, 
	 CONSTRAINT "TRUST_PK" PRIMARY KEY ("TRUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
