--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ESCHEATMENT"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"USER_NAME" VARCHAR2(40 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"MIDDLE_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"CREATE_USER_ID" VARCHAR2(40 BYTE), 
	"CREATE_DT" DATE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE), 
	"UPDATE_DT" DATE, 
	"ACTIVE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESCHEATMENT"."USERS_PK" ON "ESCHEATMENT"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ESCHEATMENT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESCHEATMENT"."USERS" MODIFY ("UPDATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USERS" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USERS" MODIFY ("CREATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USERS" MODIFY ("CREATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
