--------------------------------------------------------
--  DDL for Table USER_ROLE_ASSOC
--------------------------------------------------------

  CREATE TABLE "ESCHEATMENT"."USER_ROLE_ASSOC" 
   (	"ROLE_ASSOC_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0), 
	"ROLE_ID" NUMBER(*,0), 
	"CREATE_USER_ID" VARCHAR2(40 BYTE), 
	"CREATE_DT" DATE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE), 
	"UPDATE_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_ROLE_ASSOC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESCHEATMENT"."USER_ROLE_ASSOC_PK" ON "ESCHEATMENT"."USER_ROLE_ASSOC" ("ROLE_ASSOC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_ROLE_ASSOC
--------------------------------------------------------

  ALTER TABLE "ESCHEATMENT"."USER_ROLE_ASSOC" ADD CONSTRAINT "USER_ROLE_ASSOC_PK" PRIMARY KEY ("ROLE_ASSOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESCHEATMENT"."USER_ROLE_ASSOC" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USER_ROLE_ASSOC" MODIFY ("CREATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USER_ROLE_ASSOC" MODIFY ("CREATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USER_ROLE_ASSOC" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USER_ROLE_ASSOC" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."USER_ROLE_ASSOC" MODIFY ("ROLE_ASSOC_ID" NOT NULL ENABLE);
