--------------------------------------------------------
--  DDL for Table LOG
--------------------------------------------------------

  CREATE TABLE "ESCHEATMENT"."LOG" 
   (	"LOG_ID" NUMBER, 
	"CATEGORY" VARCHAR2(40 BYTE), 
	"PROC_NAME" VARCHAR2(40 BYTE), 
	"PROC_STATUS" VARCHAR2(20 BYTE), 
	"MESSAGE" VARCHAR2(400 BYTE), 
	"CREATE_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESCHEATMENT"."LOG_PK" ON "ESCHEATMENT"."LOG" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "ESCHEATMENT"."LOG" ADD CONSTRAINT "LOG_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESCHEATMENT"."LOG" MODIFY ("CREATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LOG" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LOG" MODIFY ("LOG_ID" NOT NULL ENABLE);
