
  CREATE TABLE "ESCHEATMENT"."LOG" 
   (	"LOG_ID" NUMBER NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PROC_NAME" VARCHAR2(40 BYTE), 
  "PROC_STATUS" VARCHAR2(20 BYTE),
	"MESSAGE" VARCHAR2(400 BYTE), 
	"CREATE_DT" DATE NOT NULL ENABLE, 
	 CONSTRAINT "LOG_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
