
  CREATE TABLE "ESCHEATMENT"."CLOCK" 
   (	"CLOCK_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CLOCK_TYPE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CLOCK_INDEX" NUMBER(*,0) NOT NULL ENABLE, 
	"LAWFUL_OWNER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TRUST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CLOCK_START" DATE NOT NULL ENABLE, 
	"CLOCK_END" DATE, 
	"CLOCK_EXPIRE_IND" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"CLOCK_STOP_IND" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"CREATE_USER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CREATE_DT" DATE NOT NULL ENABLE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"UPDATE_DT" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CLOCK_PK" PRIMARY KEY ("CLOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
