--------------------------------------------------------
--  DDL for Table CLOCK
--------------------------------------------------------

  CREATE TABLE "ESCHEATMENT"."CLOCK" 
   (	"CLOCK_ID" NUMBER(10,0), 
	"CLOCK_TYPE_ID" NUMBER(*,0), 
	"CLOCK_INDEX" NUMBER(*,0), 
	"LAWFUL_OWNER_ID" NUMBER(10,0), 
	"TRUST_ID" NUMBER(10,0), 
	"CLOCK_START" DATE, 
	"CLOCK_END" DATE, 
	"CLOCK_EXPIRE_IND" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CLOCK_STOP_IND" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CREATE_USER_ID" VARCHAR2(40 BYTE), 
	"CREATE_DT" DATE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE), 
	"UPDATE_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESCHEATMENT"."CLOCK_PK" ON "ESCHEATMENT"."CLOCK" ("CLOCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLOCK
--------------------------------------------------------

  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("UPDATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("CREATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("CREATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" ADD CONSTRAINT "CLOCK_PK" PRIMARY KEY ("CLOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("CLOCK_STOP_IND" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("CLOCK_EXPIRE_IND" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("CLOCK_START" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("TRUST_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("LAWFUL_OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("CLOCK_INDEX" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("CLOCK_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."CLOCK" MODIFY ("CLOCK_ID" NOT NULL ENABLE);
