--------------------------------------------------------
--  DDL for Table LAWFUL_OWNER
--------------------------------------------------------

  CREATE TABLE "ESCHEATMENT"."LAWFUL_OWNER" 
   (	"OWNER_ID" NUMBER(10,0), 
	"OWNER_NAME_1" VARCHAR2(255 BYTE), 
	"OWNER_ADDR_1" VARCHAR2(255 BYTE), 
	"OWNER_ADDR_2" VARCHAR2(255 BYTE), 
	"OWNER_ADDR_3" VARCHAR2(255 BYTE), 
	"TRUST_ID" NUMBER(10,0), 
	"CLOCK_INDEX" NUMBER(*,0), 
	"CREATE_USER_ID" VARCHAR2(40 BYTE), 
	"CREATE_DT" DATE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE), 
	"UPDATE_DT" DATE, 
	"OWNER_NAME_2" VARCHAR2(255 BYTE), 
	"UNDER_REVIEW" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LAWFUL_OWNER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESCHEATMENT"."LAWFUL_OWNER_PK" ON "ESCHEATMENT"."LAWFUL_OWNER" ("OWNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LAWFUL_OWNER
--------------------------------------------------------

  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" ADD CONSTRAINT "LAWFUL_OWNER_PK" PRIMARY KEY ("OWNER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" MODIFY ("UPDATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" MODIFY ("CREATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" MODIFY ("CLOCK_INDEX" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" MODIFY ("TRUST_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" MODIFY ("OWNER_ADDR_1" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" MODIFY ("OWNER_NAME_1" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."LAWFUL_OWNER" MODIFY ("OWNER_ID" NOT NULL ENABLE);
