
  CREATE TABLE "ESCHEATMENT"."LAWFUL_OWNER" 
   (	"OWNER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OWNER_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"OWNER_ADDR_1" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"OWNER_ADDR_2" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"OWNER_ADDR_3" VARCHAR2(255 BYTE), 
	"TRUST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CLOCK_INDEX" NUMBER(*,0) NOT NULL ENABLE, 
	"CREATE_USER_ID" VARCHAR2(40 BYTE), 
	"CREATE_DT" DATE NOT NULL ENABLE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"UPDATE_DT" DATE NOT NULL ENABLE, 
	 CONSTRAINT "LAWFUL_OWNER_PK" PRIMARY KEY ("OWNER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
