--------------------------------------------------------
--  DDL for Table NOTICE_SENT
--------------------------------------------------------

  CREATE TABLE "ESCHEATMENT"."NOTICE_SENT" 
   (	"NOTICE_SENT_ID" NUMBER(10,0), 
	"NOTICE_ID" NUMBER(*,0), 
	"OWNER_ID" NUMBER(10,0), 
	"NOTICE_SEND_DT" DATE, 
	"CREATE_USER_ID" VARCHAR2(40 BYTE), 
	"CREATE_DT" DATE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE), 
	"UPDATE_DT" DATE, 
	"DOCUMENT_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOTICE_SENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESCHEATMENT"."NOTICE_SENT_PK" ON "ESCHEATMENT"."NOTICE_SENT" ("NOTICE_SENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NOTICE_SENT
--------------------------------------------------------

  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" ADD CONSTRAINT "NOTICE_SENT_PK" PRIMARY KEY ("NOTICE_SENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" MODIFY ("UPDATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" MODIFY ("CREATE_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" MODIFY ("CREATE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" MODIFY ("NOTICE_SEND_DT" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" MODIFY ("OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" MODIFY ("NOTICE_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."NOTICE_SENT" MODIFY ("NOTICE_SENT_ID" NOT NULL ENABLE);
