
  CREATE TABLE "ESCHEATMENT"."PUBLICATION" 
   (	"PUBLICATION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BATCH_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FINALIZED" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"PUBLICATION_DT" DATE, 
	"OUTPUT_PDF" BLOB, 
	"CREATE_USER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CREATE_DT" DATE NOT NULL ENABLE, 
	"UPDATE_USER_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"UPDATE_DT" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PUBLICATION_PK" PRIMARY KEY ("PUBLICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("OUTPUT_PDF") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
