--------------------------------------------------------
--  DDL for Table PUBLICATION_TRUST_ASSOC
--------------------------------------------------------

  CREATE TABLE "ESCHEATMENT"."PUBLICATION_TRUST_ASSOC" 
   (	"PUB_ASSOC_ID" NUMBER(10,0), 
	"TRUST_ID" NUMBER(10,0), 
	"PUBLICATION_ID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PUBLICATION_TRUST_ASSOC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESCHEATMENT"."PUBLICATION_TRUST_ASSOC_PK" ON "ESCHEATMENT"."PUBLICATION_TRUST_ASSOC" ("PUB_ASSOC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PUBLICATION_TRUST_ASSOC
--------------------------------------------------------

  ALTER TABLE "ESCHEATMENT"."PUBLICATION_TRUST_ASSOC" ADD CONSTRAINT "PUBLICATION_TRUST_ASSOC_PK" PRIMARY KEY ("PUB_ASSOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ESCHEATMENT"."PUBLICATION_TRUST_ASSOC" MODIFY ("PUBLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."PUBLICATION_TRUST_ASSOC" MODIFY ("TRUST_ID" NOT NULL ENABLE);
  ALTER TABLE "ESCHEATMENT"."PUBLICATION_TRUST_ASSOC" MODIFY ("PUB_ASSOC_ID" NOT NULL ENABLE);
